version: "3.9"
   
services:
  app:
    build: .
    restart: always
    volumes: 
      - air-vibrations-flagging:/app/flagging
    ports:
      - 7860:7860
    networks:
      - proxynet
    expose:
      - 7860
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.air-vibrations.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.air-vibrations.entrypoints=http"

volumes:
  air-vibrations-flagging:

networks:
    proxynet:
        external:
            name: "proxynet"