version: "3.9"
   
services:
  app:
    build: .
    restart: always
    volumes: 
      - air-vibrations-flagging:/app/flagging
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_PORT=8080
      - GRADIO_SERVER_NAME=0.0.0.0
    networks:
      - proxynet
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.air-vibrations.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.air-vibrations.entrypoints=http"

volumes:
  air-vibrations-flagging:

networks:
    proxynet:
        external:
            name: "proxynet"