version: "3.9"
   
services:
  app:
    build: .
    restart: always
    volumes: 
      - air-vibrations-flagging:/app/flagging
    ports:
      - 8080:8080
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_PORT=8080
      - GRADIO_SERVER_NAME=0.0.0.0
    networks:
      - proxynet
    expose:
      - 8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airvibrations.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.airvibrations.entrypoints=http"

volumes:
  air-vibrations-flagging:

networks:
    proxynet:
        external:
            name: "proxynet"